on: 
  repository_dispatch:
    types: [server-start]

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: npm-ci
        run: npm ci

      - name: test e2e
        run: npm test     

      
        